FILE_NAME = "PLACEHOLDER"
EXCEL_FILE_NAME = "FILENAME"
EXCEL_FILE_PATH = pathlib.Path(pathlib.Path.cwd(), EXCEL_FILE_NAME)
EXCEL_APP_NUM_REGEX = r"[SWV][0-9]{9}" 
EXCEL_DATE_REGEX = r"[20][1-9]{2}"
EXCEL_SELECTED_SHEET = ''
EXCEL_FIRST_ROW = 2
EXCEL_LAST_ROW = 999
EXCEL_LAST_NAME = 2
EXCEL_FIRST_NAME = 3
EXCEL_DOB = 4
EXCEL_UCI = 5
EXCEL_NATIONALITY = 6
EXCEL_AGENT_NAME = 7
EXCEL_TYPE = 8
EXCEL_APP_NUM = 9
EXCEL_APP_SUBMISSION = 10
EXCEL_APP_REQUEST = 11
EXCEL_DECISION = 12
EXCEL_APPROVAL = 13
EXCEL_STATUS = 14
EXCEL_NOTE = 15
EXCEL_SHEETS = ["2020", "2019", "2018", "2017", "2016", "2015"]

CLIENT_APP_NUM = ''
CLIENT_AGENT_NAME = ''
CLIENT_FIRST_NAME = ''
CLIENT_LAST_NAME = ''
CLIENT_NATIONALITY = ''
CLIENT_TYPE = ''

GOOGLE_EMAIL = "ADDRESS"
GOOGLE_PW = "PW"
GOOGLE_AGENT_NAME = "James Yoo"
GOOGLE_DEPT1 = ["EMAIL1"]
GOOGLE_DEPT2 = ["EMAIL1", "EMAIL2"]
GOOGLE_DEPT3 = ["EMAIL1", "EMAIL2", "EMAIL3"]


DEPT1_AGENT = ["AGENT1"]
DEPT2_AGENT = ["AGENT2"]
DEPT3_AGENT = ["AGENT3"]
